import Head from "next/head";
import { RiMoonFoggyFill } from "react-icons/ri";
import ClipLoader from "react-spinners/ClipLoader";

import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";

import Image from "next/image";
import Footer from "../components/footers";

import { useState, useEffect } from "react";

const baseUrl = "https://api.jikan.moe/v4/anime";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [text, setText] = useState("");
  const [loading, setLoading] = useState(false);
  const [animes, setAnimes] = useState([]);

  async function searchAnime() {
    try {
      setLoading(true);
      const response = await window.fetch(`${baseUrl}?q=${text}`);
      const data = await response.json();
      setAnimes(data.data);
      setLoading(false);
      setText("");
    } catch (e) {
      setLoading(false);
      console.log(e);
    }
  }

  const handleChange = (e) => {
    setText(e.target.value);
  };

  const keyPress = (e) => {
    if (e.keyCode == 13) {
      searchAnime();
    }
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>GatotAnime</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-800 ">
        <section className="min-h-screen  ">
          <nav className="sticky top-0 z-50 py-4 rounded-b-2xl flex justify-between bg-white ">
            {/* <h1 className="text-xl text-gray-700 font-silkscreen hover:-rotate-7  cursor-pointer dark:text-white">
              TONY-PROJECT
            </h1> */}
            <ul className="flex items-center relative ">
              <li>
                <RiMoonFoggyFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-3xl text-gray-700 dark:text-gray-700 mx-6"
                />
              </li>
              <li>
                <a
                  className=" font-burtons mr-6 text-gray-600 hover:text-gray-400"
                  href="https://portofolio-tonyajipalguno.netlify.app/"
                >
                  Portofolio
                </a>
                <a
                  className=" font-burtons mr-6 text-gray-600 hover:text-gray-400"
                  href="project"
                >
                  Project
                </a>
                <a
                  className=" font-burtons mr-6 text-gray-600 hover:text-gray-400"
                  href="blog"
                >
                  Blog
                </a>
              </li>
            </ul>
            <ul className="flex items-center ">
              <li>
                <a
                  className=" font-silkscreen bg-gradient-to-r from-pink-500 to-sky-400 hover:from-pink-400 hover:to-sky-300 text-white px-4 py-2 rounded mr-5"
                  href="https://drive.google.com/file/d/1pLf1l7aqjoOJ1V3uvF8_NlLGaC2bSDdj/view"
                >
                  Hire Me
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center px-10 py-10 mt-16 ">
            <div className="relative w-full max-w-7xl dark:bg-none">
              <h2 className="text-transparent bg-clip-text bg-gradient-to-r from-pink-500 to-sky-500 hover:from-pink-400 hover:to-sky-300 text-5xl font-silkscreen font-semibold ">
                Gatot KACA
              </h2>
              <h3 className="font-burtons text-lg text-slate-400 pt-2">
                search api
              </h3>

              {/* searchbar */}
              <div className="mb-14 md:w-[584px] mx-auto mt-7 flex w-[90%] items-center rounded-full border hover:shadow-sm">
                <div className="pl-5">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-6 w-6 text-gray-400 dark:text-gray-300"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth="2"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                    />
                  </svg>
                </div>
                <input
                  type="text"
                  id="textSearch"
                  className="dark:text-white w-full bg-transparent rounded-full py-[14px] pl-4 outline-none"
                  placeholder="Search.."
                  value={text}
                  onChange={handleChange}
                  onKeyDown={keyPress}
                />
                <div class="">
                  <button
                    onClick={searchAnime}
                    type="submit"
                    id="btnSearch"
                    className="font-burtons tracking-wide bg-pink-500 hover:bg-pink-600 rounded-r-3xl rounded-bl-3xl border-r-4 border-pink-600 text-white  py-3.5 xl:px-9 sm:px-7"
                  >
                    Submit
                  </button>
                </div>
              </div>

              <div>
                {loading && (
                  <div className="dark:text-white text-center">
                    <ClipLoader
                      color="#b380b7"
                      size={50}
                      aria-label="Loading Spinner"
                      data-testid="loader"
                    />
                  </div>
                )}
              </div>

              {/*  */}
              <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 w-full">
                {!loading &&
                  animes &&
                  animes.map((anime) => (
                    <div
                      key={anime.mal_id}
                      className="flex flex-row xl:flex-row shadow hover:shadow-md w-full bg-white rounded-lg overflow-hidden cursor-pointer"
                    >
                      <img
                        className="object-cover sm:w-32 md:w-48 md:h-48"
                        src={anime.images.webp.large_image_url}
                        alt="animeImage"
                      />

                      <div className="relative p-3">
                        <h3 className=" md:text-md font-medium text-gray-800">
                          {anime.title}
                        </h3>
                        <h4 className="text-xs">{anime.aired.string}</h4>

                        <p className="mt-4 text-justify text-xs md:text-xs text-gray-600">
                          {anime.title_japanese}
                        </p>
                      </div>
                    </div>
                  ))}
              </div>
              {/*  */}
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
